import './globals.css';

import { ThemeModeScript } from 'flowbite-react';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Despartamentos Mar del Plata",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,team,analytics
}: Readonly<{
  children: React.ReactNode,
  analytics: React.ReactNode,
  team: React.ReactNode
}>) {
  return (
    <html lang="en">
          <head>
      <ThemeModeScript />
    </head>
      <body className={inter.className}>{children} {team} {analytics}</body>
    </html>
  );
}
